#+TITLE: Appearance
#+PROPERTY: header-args      :tangle "../config-elisp/appearance.el"
* Bar Cursor
Change Emacs cursor into a bar.

https://github.com/ajsquared/bar-cursor
#+begin_src emacs-lisp
  (use-package bar-cursor
    :ensure t
    :hook ((after-init . bar-cursor-mode)
	   (after-init . blink-cursor-mode)))
#+end_src
* Circadian
Theme-switching for Emacs based on daytime.

https://github.com/GuidoSchmidt/circadian.el
#+begin_src emacs-lisp
  (use-package circadian
    :ensure t
    :custom
    (circadian-themes '(("7:00"  . modus-operandi)
			("17:30" . modus-vivendi)))
    :hook (after-init . circadian-setup))
#+end_src
* Fira Code Ligatures
Emacs minor mode for Fira Code ligatures using prettify-symbols.

https://github.com/jming422/fira-code-mode
#+begin_src emacs-lisp
  (use-package fira-code-mode
    :ensure t
    :config (fira-code-mode-set-font)
    :hook prog-mode)
#+end_src
* Font Face
Set the default face font attribute. 
#+begin_src emacs-lisp
  (set-face-attribute 'default nil :font "Iosevka 14")
#+end_src
* Line Truncation
Never truncate lines by default. 
#+begin_src emacs-lisp
  (setq-default truncate-lines -1)
#+end_src
* Modern Fringes
Replaces the ugly looking default emacs fringe bitmaps and replaces them with better, modern looking ones.

https://github.com/SpecialBomb/emacs-modern-fringes
#+begin_src emacs-lisp
  (use-package modern-fringes
    :ensure t
    :hook (after-init . modern-fringes-mode)
    :config (set-fringe-mode '(7 . 0)))
#+end_src
* Prettify Symbols
When Prettify Symbols mode and font-locking are enabled, symbols are prettified (displayed as composed characters) according to the rules in `prettify-symbols-alist' (which see), which are locally defined by major modes supporting prettifying.
#+begin_src emacs-lisp
  (global-prettify-symbols-mode t)
#+end_src
* Time
Display time in the mode line as 12-hour clock with am/pm. 
#+begin_src emacs-lisp
  (setq display-time-default-load-average nil
        display-time-format "%I:%M%p")
  (display-time-mode t)
#+end_src
